[COINGECKO_API_KEY]
CG-gpn39ZBd8Tu3mRmuxQGsYN5S = ""

[ETHEREUM_RPC_URL]
https://sepolia.infura.io/v3/f3be09a17c2d424ab3d5ef1de758e4bc = ""

[CONTRACT_ADDRESS]
0xd0214254f898F8855C73Bd1bBD080Cb5a06A131e = ""

[DEBUG]
false = ""

[LOG_LEVEL]
INFO = "" 